# ----
# Site

title: Urban Flow
description: Urban Flow Jekyll template for API documentation.
url: https://deepurban.kaist.ac.kr/
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position_number: 1
  api:
    title: APIs
    position_number: 2
  visualization:
    title: Visualization
    position_number: 3
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true
  -
    scope:
      type: "visualization"
    values:
      _hide_content: true
      
# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post
  - viz

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
